### ISSUE TITLE
Embedding not working

### ISSUE THREAD

**Issue by sumew** [bitnami/bitnami-docker-ghost#95] opened 2020-11-27 03:58 UTC
**Description**
Embedding not working

**Steps to reproduce the issue:**

1. Create a new post
2. Click the + sign and choose embed
3. paste the embed script and enter

**Describe the results you received:**

On the browser: `There was an error when parsing the URL.`, console shows http error 422
In the container:

```
NAME: ValidationError
MESSAGE: No provider found for supplied URL.

level: normal

ValidationError: No provider found for supplied URL.
    at new ValidationError (/opt/bitnami/ghost/versions/3.38.2/node_modules/ghost-ignition/lib/errors/index.js:141:23)
    at unknownProvider (/opt/bitnami/ghost/versions/3.38.2/core/server/api/canary/oembed.js:81:27)
    at fetchOembedData (/opt/bitnami/ghost/versions/3.38.2/core/server/api/canary/oembed.js:124:16)
    at Object.query (/opt/bitnami/ghost/versions/3.38.2/core/server/api/canary/oembed.js:250:20)
    at Object.query (/opt/bitnami/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:156:24)
    at Promise.resolve.then.then.then.then (/opt/bitnami/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:243:35)
    at tryCatcher (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/bitnami/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)```



`3.38.2-debian-10-r0`

```
Docker version 19.03.6, build 369ce74a3c
```

Bare metal

**Comment by dani8art** [comment] 2020-11-27 15:06
Hi @sumew,  thank you so much for your feedback, I can confirm that I was able to reproduce the issue, we have created an internal task to evaluate and check it, unfortunately, due to the fact that we are a small team and taking into account internal milestone, we can't give you an ETA for the fix.

We'll keep in contact.

**Comment by juan131** [comment] 2021-06-30 15:11
Hi @sumew 

I just tried the latest Ghost image and found no issues adding embedded objects (in my case I used a Spotify link). I'm closing the issue, but please feel free to reopen it if you're still struggling with it.

**Closed by juan131** 2021-06-30 15:11 UTC
Labels: on-hold
