### ISSUE TITLE
It can't comes up.

### ISSUE THREAD

**Issue by meeeo** [bitnami/bitnami-docker-ghost#62] opened 2017-12-20 09:40 UTC
It won't come up with passwords set at first:
  https://asciinema.org/a/153582
So I thought there might be something wrong with my configs,
but it still can't comes up with your yaml file:
  https://asciinema.org/a/153597
I don't know where is the problem.
Thanks for your hardwork and patients.

**Comment by javsalgar** [comment] 2017-12-20 10:24
Hi,

I am unable to reproduce the issue. As you can see here, it works without issues. https://asciinema.org/a/aXr1J73CgDbQtZzDS7HTvIfX2

```
○ → docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: 4OQ7:T5HZ:YUXW:Y6O7:2QWG:RYBN:JBOZ:L3GL:WSK5:X6QM:MEUV:FB26
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 53
 System Time: 2017-12-20T10:22:13.762441174Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
Could you provide more details of your docker environment?

**Comment by meeeo** [comment] 2017-12-20 14:00
@javsalgar Hi, thank you, here's my docker environment information:
root@toys:~/devastator/test# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 17.11.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5MiB
Name: toys.localdomain
ID: T67O:AA7P:LYH2:YESE:WNG5:4SKU:DW6N:463S:TUY2:4AD4:VRZF:DOVD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
root@toys:~/devastator/test#

**Comment by meeeo** [comment] 2017-12-20 15:40
I turned off the apparmor service, still the same, I'll try another host tomorrow, thank you.

**Comment by meeeo** [comment] 2017-12-21 07:27
I tried it on my laptop, nothing wrong.
That's strange.
<img width="720" alt="screenshot" src="https://user-images.githubusercontent.com/5188710/34245025-10a54f18-e663-11e7-8961-8dc35e4fd182.png">

**Comment by meeeo** [comment] 2017-12-21 08:30
Tried on another host, failed again with different error massages:
<img width="1440" alt="2017-12-21 16 07 17" src="https://user-images.githubusercontent.com/5188710/34246988-cdd51458-e66b-11e7-84dc-aae9eb178d9a.png">
They are both regular vms created on DigitalOcean, no special settings:
<img width="1267" alt="2017-12-21 16 25 40" src="https://user-images.githubusercontent.com/5188710/34247046-1690451e-e66c-11e7-8901-b5cf23b656be.png">
Maybe lack of memory?

**Comment by javsalgar** [comment] 2017-12-21 10:41
Hi,

The memory issue makes sense to me (1 GB is not too much). Could you try with a bigger instance?

**Comment by meeeo** [comment] 2017-12-22 07:56
I temporarily resized to a 4GB memory instance, still the same, don't know why.
<img width="1440" alt="2017-12-22 15 40 59" src="https://user-images.githubusercontent.com/5188710/34289759-f8407fc0-e72e-11e7-972c-074d55abe960.png">
Switched to other solution, maybe I'll try this another day, thank you for your hard working.

**Comment by chipironcin** [comment] 2017-12-27 13:24
Hi @meeeo 
Are you cleaning Docker volumes and stale containers between tries?
```
docker-compose down -v && docker-compose pull && docker-compose up --build --force-recreate```

**Comment by meeeo** [comment] 2017-12-28 07:14
@chipironcin 
Thanks for your advice，I'll try this later

**Comment by sameersbn** [comment] 2017-12-28 09:38
I tried the docker-compose.yml file on a DO 1GB/30GB instance and faced no issues.

Here's my setup:

```bash
$ apt-get -y install apt-transport-https ca-certificates curl && \
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
apt-get -y update && \
apt-get -y install docker-ce python-pip && pip install -U docker-compose


$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false


$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: ubuntu-1gb-sfo2-01
ID: TO7K:7JSM:IRVN:U2K7:XVWY:CPB3:XMB2:NENH:F7UN:QWQL:QTHM:GNDE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support


$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.7.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

And to boot up ghost:

```bash
$ mkdir ghost && \
  cd ghost/ && \
  curl -sSLO https://raw.githubusercontent.com/bitnami/bitnami-docker-ghost/master/docker-compose.yml && \
  docker-compose up
```

Everything went without any issues...

**Option 1:**

Remove any containers, volumes, upgrade images and retry as @chipironcin suggested

```bash
# note: this removed any associated volumes and thereby , i think it should be fine in your case since you haven't been able to bring up ghost before.
docker-compose down -v
docker-compose pull
docker-compose up
```

**Option 2:**

Upgrade docker to latest release and execute steps from option 1.

```bash
$ apt-get install --only-upgrade docker-ce
```

**Option 3:**

_**Try this if all else fails.**_

reset docker and retry.. 

Note: This will remove any existing images and running containers. If the system does not have any other running containers this should be fine... 

```bash
$ systemctl stop docker && \
   rm -rf /var/lib/docker && \
   systemctl start docker
```

Next, follow steps from option 1.

Please let us know what works for you.

**Comment by dbarranco** [comment] 2018-01-15 13:36
We proceed to close this issue as it has not received any new comment since 18 days ago. 

If you still find any issue related to this, please, do not hesitate on opening a new issue.
Thanks!

**Closed by dbarranco** 2018-01-15 13:36 UTC
